/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import manipuladoresDAO.AdministrativoDAO;
import manipuladoresDAO.CalificacionDAO;
import manipuladoresDAO.MateriaDAO;
import Modelo.Administrativo;
import universidadulp_grupo5.Alumno;
import universidadulp_grupo5.Calificacion;
import universidadulp_grupo5.Materia;

/**
 *
 * @author Enzo_2
 */
public class ConsultaInscInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaInscInternal
     */
    private MateriaDAO maniMateria = new MateriaDAO();
    private CalificacionDAO maniCal = new CalificacionDAO();
    private AdministrativoDAO maniAdmin = new AdministrativoDAO();
    private HashMap<Integer, Materia> listaMaterias;
    private HashMap<Integer, ArrayList<Calificacion>> listaCalificacionesXmateria;
    private Alumno alumno;

    public ConsultaInscInternal(Alumno alumno) {
        this.alumno = alumno;
        initComponents();
        this.setResizable(false);
        cambiarLabels();
        rellenarHashMapListas();
        rellenarCabeceras(tblCalificaciones);
        listaInscripciones(listMateriasInscriptas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalificaciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMateriasInscriptas = new javax.swing.JList<>();
        lblDNI = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(47, 96, 131));

        tblCalificaciones.setBackground(new java.awt.Color(222, 222, 222));
        tblCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCalificaciones);

        listMateriasInscriptas.setBackground(new java.awt.Color(222, 222, 222));
        listMateriasInscriptas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materias inscriptas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        listMateriasInscriptas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listMateriasInscriptas.setSelectionBackground(new java.awt.Color(153, 0, 0));
        listMateriasInscriptas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listMateriasInscriptas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMateriasInscriptasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listMateriasInscriptas);

        lblDNI.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI.setText("DNIEJEMPLO");

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("NOMBREEJEMPLO");

        lblApellido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("APELLIDOEJEMPLO");

        lblFechaNacimiento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setText("FECHANACIMIENTOEJEMPLO");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Consulta de clasificaciones");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de nacimiento:");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DNI:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellido)
                                    .addComponent(lblFechaNacimiento)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(lblNombre)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 27, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMateriasInscriptasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMateriasInscriptasValueChanged
        String completo = listMateriasInscriptas.getSelectedValue();
        String[] cortado = completo.split(" - ");
        String idInsString = cortado[1];
        Integer idIns = Integer.parseInt(idInsString);
        try {
            if (!listMateriasInscriptas.getValueIsAdjusting()) {
                return;
            }
            rellenarTabla(idIns);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las calificaciones");
        }
    }//GEN-LAST:event_listMateriasInscriptasValueChanged

    private void rellenarCabeceras(JTable tabla) {
        String[] cabeceras = {"Nombre administrativo", "Tipo de evaluación", "Calificación", "Fecha de subida"};
        DefaultTableModel model = new DefaultTableModel(null, cabeceras) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(model);
    }

    private void rellenarHashMapListas() {
        //La clave es el id de inscripción
        listaMaterias = maniMateria.listarMateriaXidInscripcionPorAlumno(alumno.getId_alumno());
        listaCalificacionesXmateria = maniCal.IDinscripcionXCalificacionesPorIdAlumno(alumno.getId_alumno());

    }

    private void cambiarLabels() {
        lblDNI.setText(Integer.toString(alumno.getDni()));
        lblNombre.setText(alumno.getNombre());
        lblApellido.setText(alumno.getApellido());
        lblFechaNacimiento.setText(alumno.getFecha_nacimiento().toString());
    }

    private void listaInscripciones(JList lista) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Map.Entry<Integer, Materia> entry : listaMaterias.entrySet()) {
            String nombre = entry.getValue().getNombre();
            String idInscripcion = Integer.toString(entry.getKey());
            String item = nombre + " - " + idInscripcion;
            model.addElement(item);
        }
        lista.setModel(model);
    }

    private void rellenarTabla(Integer idInscripcion) {
        DefaultTableModel modelo = (DefaultTableModel) tblCalificaciones.getModel();
        modelo.setRowCount(0);
        for (Map.Entry<Integer, ArrayList<Calificacion>> m : listaCalificacionesXmateria.entrySet()) {
            if (m.getKey().equals(idInscripcion)) {
                ArrayList<Calificacion> lista = m.getValue();
                for (Calificacion cal : lista) {
                    Administrativo admin = maniAdmin.buscarPorId(cal.getId_administrativo());
                    modelo.addRow(new Object[]{admin.getNombre() + " " + admin.getApellido(),
                        Double.toString(cal.getCalificacion()),
                        cal.getFechaModificacion().toString()});
                }
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> listMateriasInscriptas;
    private javax.swing.JTable tblCalificaciones;
    // End of variables declaration//GEN-END:variables
}
