/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import manipuladoresDAO.AlumnoDAO;
import manipuladoresDAO.CalificacionDAO;
import Modelo.Alumno;
import Modelo.Calificacion;

/**
 *
 * @author Enzo_2
 */
public class DialogCalificacion extends javax.swing.JDialog {

    /**
     * Creates new form DialogCalificacion
     */
    private AlumnoDAO maniAlum = new AlumnoDAO();
    private CalificacionDAO maniCal = new CalificacionDAO();
    int idAd;
    int idAl;
    int idIns;
    String nMateria;
    public DialogCalificacion(java.awt.Frame parent, boolean modal,String nombreM,int idIns ,int idAdministrativo, int idAlumno) {
        super(parent, modal);
        this.idAl = idAlumno;
        this.idAd = idAdministrativo;
        this.nMateria = nombreM;
        this.idIns = idIns;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgregar = new javax.swing.JPanel();
        txtCalificacion = new javax.swing.JTextField();
        txtTipoEvaluacion = new javax.swing.JTextField();
        lblCalificacion = new javax.swing.JLabel();
        lblTipoEvaluacion = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblAgregarC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAgregar.setBackground(new java.awt.Color(47, 96, 131));

        txtCalificacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        txtTipoEvaluacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblCalificacion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCalificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCalificacion.setText("Calificación:");

        lblTipoEvaluacion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTipoEvaluacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoEvaluacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoEvaluacion.setText("Tipo de evaluación:");

        btnAgregar.setBackground(new java.awt.Color(47, 96, 131));
        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar calificación");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(47, 96, 131));
        btnLimpiar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(47, 96, 131));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblAgregarC.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblAgregarC.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarC.setText("AGREGAR CALIFICACION");

        javax.swing.GroupLayout pnlAgregarLayout = new javax.swing.GroupLayout(pnlAgregar);
        pnlAgregar.setLayout(pnlAgregarLayout);
        pnlAgregarLayout.setHorizontalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoEvaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipoEvaluacion)
                    .addComponent(txtCalificacion)
                    .addGroup(pnlAgregarLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(41, 41, 41)
                        .addComponent(btnLimpiar))
                    .addComponent(lblCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAgregarLayout.setVerticalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAgregarC)
                .addGap(18, 18, 18)
                .addComponent(lblTipoEvaluacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCalificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCalificacion.setText("");
        txtTipoEvaluacion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Alumno alumno = null;
        String tipoEvaluacion = txtTipoEvaluacion.getText();
        String calificacion = txtCalificacion.getText();
        if(tipoEvaluacion.isEmpty()||calificacion.isEmpty()){
            JOptionPane.showMessageDialog(this, "Rellene todos los campos correctamente.");
            return;
        }
        try {
            Double calificacionParseada = Double.parseDouble(calificacion);
            if(calificacionParseada < 1.0 || calificacionParseada > 10.00){
                JOptionPane.showMessageDialog(this, "Ingrese una calificacion entre 1.00 y 10.00");
                return;
            }
            alumno = maniAlum.buscarPorId(idAl);
            int seleccion = JOptionPane.showConfirmDialog(this, 
                    "¿Esta seguro que desea agregar la calificacion al alumno: "
                    + alumno.getApellido() + " " + alumno.getNombre()
                            + " con DNI: " + alumno.getDni() + " a la materia "
                    + nMateria + "?", "CONFIRMACION", YES_NO_OPTION);
            if(seleccion == 0){
                Calificacion cal = new Calificacion(idIns, idAd, tipoEvaluacion, calificacionParseada);
                maniCal.agregar(cal);
                JOptionPane.showMessageDialog(this, "Calificación agregada correctamente.");
            }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese una calificación valida.");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al agregar calificación.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblAgregarC;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblTipoEvaluacion;
    private javax.swing.JPanel pnlAgregar;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtTipoEvaluacion;
    // End of variables declaration//GEN-END:variables
}
