/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.List;
import javax.swing.JOptionPane;
import manipuladoresDAO.MateriaDAO;
import Modelo.Materia;

/**
 *
 * @author USUARIO
 */
public class DialogMateria extends javax.swing.JDialog {

    /**
     * Creates new form DialogMateria
     */
    private MateriaDAO maniMateria = new MateriaDAO();
    private List<Materia> listaMaterias = maniMateria.listar();
    
    public DialogMateria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelAgregarMateria = new javax.swing.JPanel();
        lblAgregarMateria = new javax.swing.JLabel();
        lblNombreMateria = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        lblDescripcionMateria = new javax.swing.JLabel();
        txtDescripcionMateria = new javax.swing.JTextField();
        lblCodigoMateria = new javax.swing.JLabel();
        txtCodigoMateria = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(47, 96, 131));
        setForeground(new java.awt.Color(47, 96, 131));

        jPanelAgregarMateria.setBackground(new java.awt.Color(47, 96, 131));

        lblAgregarMateria.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblAgregarMateria.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarMateria.setText("AGREGAR MATERIA");

        lblNombreMateria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNombreMateria.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreMateria.setText("Nombre de la materia:");

        txtNombreMateria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreMateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDescripcionMateria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblDescripcionMateria.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcionMateria.setText("Descripción de la materia:");

        txtDescripcionMateria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDescripcionMateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCodigoMateria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCodigoMateria.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigoMateria.setText("Código de la materia:");

        txtCodigoMateria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCodigoMateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAgregar.setBackground(new java.awt.Color(47, 96, 131));
        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(47, 96, 131));
        btnLimpiarCampos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(47, 96, 131));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarMateriaLayout = new javax.swing.GroupLayout(jPanelAgregarMateria);
        jPanelAgregarMateria.setLayout(jPanelAgregarMateriaLayout);
        jPanelAgregarMateriaLayout.setHorizontalGroup(
            jPanelAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgregarMateriaLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtDescripcionMateria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoMateria)
                            .addComponent(lblCodigoMateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAgregarMateriaLayout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarCampos)
                                .addGap(31, 31, 31)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblNombreMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDescripcionMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblAgregarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelAgregarMateriaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAgregarMateriaLayout.setVerticalGroup(
            jPanelAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarMateriaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAgregarMateria)
                .addGap(18, 18, 18)
                .addComponent(lblNombreMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcionMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCodigoMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarCampos)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAgregarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAgregarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombreMateria.getText();
        String descripcion = txtDescripcionMateria.getText();
        String codigo = txtCodigoMateria.getText();
        if(nombre.isEmpty() || descripcion.isEmpty() || codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Rellene todos los campos necesario.");
            return;
        }
        
        try{
        boolean estado = true;
        Materia materia = new Materia(nombre, descripcion, codigo, estado); 
            if(!listaMaterias.contains(materia)){
            maniMateria.agregar(materia);
            JOptionPane.showMessageDialog(this, "Materia agregada correctamente.");
            limpiarCampos();
            }else{
            JOptionPane.showMessageDialog(this, "Ya existe una materia con ese código de materia.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al agregar materia.");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void limpiarCampos(){
        txtNombreMateria.setText("");
        txtDescripcionMateria.setText("");
        txtCodigoMateria.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMateria dialog = new DialogMateria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAgregarMateria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAgregarMateria;
    private javax.swing.JLabel lblCodigoMateria;
    private javax.swing.JLabel lblDescripcionMateria;
    private javax.swing.JLabel lblNombreMateria;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txtCodigoMateria;
    private javax.swing.JTextField txtDescripcionMateria;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
