/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import manipuladoresDAO.MateriaDAO;
import universidadulp_grupo5.Alumno;
import universidadulp_grupo5.Inscripcion;
import universidadulp_grupo5.Materia;

/**
 *
 * @author Enzo_2
 */
public class InscripcionInternal extends javax.swing.JInternalFrame {

    private MateriaDAO listMateri = new MateriaDAO();
    private Alumno alumno = new Alumno();
    
    public InscripcionInternal(Alumno alumno) {
        
        initComponents();
    rellenarCabecera(tblMateria);
    RellenarTabla(tblMateria);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnInscribirse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateria = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Inscripcion de Materias ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Elija la materia");

        BtnInscribirse.setText("Inscribirse");
        BtnInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInscribirseActionPerformed(evt);
            }
        });

        tblMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMateria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BtnInscribirse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnInscribirse)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInscribirseActionPerformed
      
       int filaMateria = tblMateria.getSelectedRow();
    int filaUsuario = tblMateria.getSelectedRow();

    if (filaMateria == -1 || filaUsuario == -1) {
        JOptionPane.showMessageDialog(null, "Selecciona una materia y un usuario.");
        return;
    }

    int id_materia = Integer.parseInt(tblMateria.getValueAt(filaMateria, 0).toString());
    int id_usuario = Integer.parseInt(tblMateria.getValueAt(filaUsuario, 0).toString());

    try {
        Connection con = DriverManager.getConnection("jdbc:mariadb://localhost/gp5_universidadulp", "root", "");

        PreparedStatement check = con.prepareStatement(
        "SELECT * FROM inscripcion WHERE id_alumno = ? AND id_materia = ?"
        );
        check.setInt(1, id_usuario);
        check.setInt(2, id_materia);
        ResultSet rs = check.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "El usuario ya está inscripto en esta materia.");
            return;
        }

        // Insertar inscripción
        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO inscripcion (id_usuario, id_materia, estado) VALUES (?, ?, ?)"
        );
        ps.setInt(1, id_usuario);
        ps.setInt(2, id_materia);
        ps.setBoolean(3, true);

        int filas = ps.executeUpdate();
        if (filas > 0) {
            JOptionPane.showMessageDialog(null, "Inscripción realizada con éxito 🎉");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la inscripción.");
        }

        ps.close();
        con.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error de base de datos: " + ex.getMessage());
    }
 
    }//GEN-LAST:event_BtnInscribirseActionPerformed
 public void rellenarCabecera(JTable tabla){
            
            DefaultTableModel model = new DefaultTableModel(){
        @Override
            public boolean isCellEditable(int a, int b) {
                return false;
            }
        
        };
            model.addColumn("id_materia");
        model.addColumn("nombre");
        model.addColumn("descripcion");
        model.addColumn("estado");
            tabla.setModel(model);
        }
    public void RellenarTabla (JTable tabla){
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        try{
            List<Materia> listarMaterias = listMateri.listar();
            for(Materia m : listarMaterias){
                if(m.isEstado() != false){
                   modelo.addRow(new Object[]{m.getId_materia(),m.getNombre(),m.getDescripcion(),m.isEstado()});
                }else{
                    modelo.addRow(new Object[]{m.getId_materia(),m.getNombre(),m.getDescripcion(),m.isEstado()});
                }
            }  
        }catch (Exception e){
            JOptionPane.showMessageDialog(tabla, "error al cargar las materias");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInscribirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMateria;
    // End of variables declaration//GEN-END:variables

    
       
    
    
  
}
