/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import manipuladoresDAO.InscripcionDAO;
import manipuladoresDAO.MateriaDAO;
import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import java.util.ArrayList;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Enzo_2
 */
public class InscripcionInternal extends javax.swing.JInternalFrame {

    private MateriaDAO listMateri = new MateriaDAO();
    private InscripcionDAO maniIns = new InscripcionDAO();
    private int seleccionMat = -1;
    private int seleccionIns = -1;
    List<Inscripcion> listaInscripciones; 
    private Alumno alumno;
    public InscripcionInternal(Alumno alumno) {
        this.alumno = alumno;
        initComponents();
        rellenarCabeceraMateriasDisponibles(tblMaterias);
        rellenarCabeceraInscripciones(tblInscripciones);
        rellenarTabla(tblMaterias);
        agregarActionListener(tblMaterias);
        btnInscribirse.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInscripcionMaterias = new javax.swing.JLabel();
        lblSelMateria = new javax.swing.JLabel();
        btnInscribirse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInscripciones = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        lblOfertaMaterias = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        lblMisInscripciones = new javax.swing.JLabel();
        lblSelInscrip = new javax.swing.JLabel();
        lblMateriaSel = new javax.swing.JLabel();
        txtMateriaS = new javax.swing.JTextField();
        txtCodigoMateriaS = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionS = new javax.swing.JTextArea();
        lblNombre = new javax.swing.JLabel();
        lblCodMateria = new javax.swing.JLabel();
        btnBaja = new javax.swing.JButton();
        jSeparador = new javax.swing.JSeparator();
        checkEdicion = new javax.swing.JCheckBox();
        btnEliminar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        lblInscripSel = new javax.swing.JLabel();
        txtFechaS = new javax.swing.JTextField();
        txtInscripcionS = new javax.swing.JTextField();
        lblMateria = new javax.swing.JLabel();
        lblFechaInscrip = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInscripcionMaterias.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblInscripcionMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInscripcionMaterias.setText("Inscripcion de Materias ");
        getContentPane().add(lblInscripcionMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, 20));

        lblSelMateria.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        lblSelMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelMateria.setText("Seleccione la materia a la cual desea inscribirse");
        getContentPane().add(lblSelMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, -1));

        btnInscribirse.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnInscribirse.setText("Agregar inscripción");
        btnInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirseActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscribirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, -1));

        tblInscripciones.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        tblInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInscripciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 380, 290));

        btnSalir.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 100, -1));

        lblOfertaMaterias.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblOfertaMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOfertaMaterias.setText("Oferta de materias");
        getContentPane().add(lblOfertaMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 370, -1));

        tblMaterias.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblMaterias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 86, 380, 290));

        lblMisInscripciones.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMisInscripciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMisInscripciones.setText("Mis Inscripciones");
        getContentPane().add(lblMisInscripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 30, 380, -1));

        lblSelInscrip.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        lblSelInscrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelInscrip.setText("Seleccione una inscripción que quiera modificar");
        getContentPane().add(lblSelInscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 310, -1));

        lblMateriaSel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblMateriaSel.setText("Materia seleccionada:");
        getContentPane().add(lblMateriaSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        txtMateriaS.setEditable(false);
        txtMateriaS.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        getContentPane().add(txtMateriaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 90, -1));

        txtCodigoMateriaS.setEditable(false);
        txtCodigoMateriaS.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        getContentPane().add(txtCodigoMateriaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 80, -1));

        txtDescripcionS.setEditable(false);
        txtDescripcionS.setColumns(20);
        txtDescripcionS.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtDescripcionS.setRows(5);
        jScrollPane3.setViewportView(txtDescripcionS);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 320, 80));

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 20));

        lblCodMateria.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblCodMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodMateria.setText("Cod. materia:");
        getContentPane().add(lblCodMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, 20));

        btnBaja.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnBaja.setText("Dar de Baja");
        getContentPane().add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, -1, -1));

        jSeparador.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 10, 540));

        checkEdicion.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        checkEdicion.setText("Hablitar modificación de inscripciones");
        getContentPane().add(checkEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        btnAlta.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnAlta.setText("Dar de Alta");
        getContentPane().add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        lblInscripSel.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblInscripSel.setText("Inscripción seleccionada:");
        getContentPane().add(lblInscripSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        txtFechaS.setEditable(false);
        txtFechaS.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        getContentPane().add(txtFechaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 160, 30));

        txtInscripcionS.setEditable(false);
        txtInscripcionS.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        getContentPane().add(txtInscripcionS, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 160, -1));

        lblMateria.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMateria.setText("Materia:");
        getContentPane().add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, 20));

        lblFechaInscrip.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblFechaInscrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaInscrip.setText("Fecha inscripción:");
        getContentPane().add(lblFechaInscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 516, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirseActionPerformed
        Inscripcion inscrip = null;
        try {
            inscrip = new Inscripcion(alumno.getId_alumno(), seleccionMat, true);
            maniIns.agregar(inscrip);
            JOptionPane.showMessageDialog(this, "inscripcion realizada con exito ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error al eliminar una materia ");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInscribirseActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();                           
    }//GEN-LAST:event_btnSalirActionPerformed
    private void rellenarCabeceraInscripciones(JTable tabla){
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int a, int b) {
                return false;
            }

        };
        model.addColumn("id_inscripcion");
        model.addColumn("Nombre materia");
        model.addColumn("Fecha inscripción");
        model.addColumn("Estado inscripción");
        tabla.setModel(model);
        TableColumnModel modeloColm = tabla.getColumnModel();
        TableColumn column0 = modeloColm.getColumn(0);
        column0.setMinWidth(0);
        column0.setMaxWidth(0);
        column0.setPreferredWidth(0);
        column0.setResizable(false);
    }
    public void rellenarCabeceraMateriasDisponibles(JTable tabla) {

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int a, int b) {
                return false;
            }

        };
        model.addColumn("id_materia");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Codigo materia");
        tabla.setModel(model);
        TableColumnModel modeloColm = tabla.getColumnModel();
        TableColumn column0 = modeloColm.getColumn(0);
        column0.setMinWidth(0);
        column0.setMaxWidth(0);
        column0.setPreferredWidth(0);
        column0.setResizable(false);
    }

    public void rellenarTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        listaInscripciones = maniIns.listarInscripcionesPorAlumno(alumno.getId_alumno());
        modelo.setRowCount(0);
        ArrayList<Materia> listaMateriasFiltrada = new ArrayList<>();
        try {
            List<Materia> listarMaterias = listMateri.listar();
            for (Inscripcion i : listaInscripciones) {
                for(Materia m : listarMaterias){
                    if(i.getId_materia() != m.getId_materia() && m.isEstado() && !listaMateriasFiltrada.contains(m)){
                        listaMateriasFiltrada.add(m);
                    }
                } 
            }
            for(Materia m : listaMateriasFiltrada){
                modelo.addRow(new Object[]{m.getId_materia(), m.getNombre(), 
                        m.getDescripcion(),
                        m.getCodigo_materia()
                        });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabla, "error al cargar las materias");
        }
    }

    public void agregarActionListener(JTable tabla) {
        tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent eventos) {
                if (eventos.getValueIsAdjusting()) {
                    return;
                }
                int filaMateria = tabla.getSelectedRow();
                if (filaMateria > - 1) {
                    seleccionMat = (int) tabla.getValueAt(filaMateria, 0);
                    btnInscribirse.setEnabled(true);
                } else {
                    btnInscribirse.setEnabled(false);
                }
            }

        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInscribirse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox checkEdicion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparador;
    private javax.swing.JLabel lblCodMateria;
    private javax.swing.JLabel lblFechaInscrip;
    private javax.swing.JLabel lblInscripSel;
    private javax.swing.JLabel lblInscripcionMaterias;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblMateriaSel;
    private javax.swing.JLabel lblMisInscripciones;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOfertaMaterias;
    private javax.swing.JLabel lblSelInscrip;
    private javax.swing.JLabel lblSelMateria;
    private javax.swing.JTable tblInscripciones;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTextField txtCodigoMateriaS;
    private javax.swing.JTextArea txtDescripcionS;
    private javax.swing.JTextField txtFechaS;
    private javax.swing.JTextField txtInscripcionS;
    private javax.swing.JTextField txtMateriaS;
    // End of variables declaration//GEN-END:variables

}
