/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Administrativo;

/**
 *
 * @author Enzo_2
 */
public class VistaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form VistaAlumno
     */
    private Administrativo usuario;
    
    public VistaAlumno(Administrativo usuario) {
        this.usuario = usuario;
        initComponents();
        javax.swing.SwingUtilities.updateComponentTreeUI(this);
        this.setSize(1100, 730);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnMaterias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnCalificaciones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenu1.setText("Alumnos");

        btnAlumnos.setText("Gestión de alumnos");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(btnAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        btnMaterias.setText("Gestión de materias");
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(btnMaterias);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Calificaciones");

        btnCalificaciones.setText("Calificaciones");
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });
        jMenu5.add(btnCalificaciones);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Salir");

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cerrar sesión");

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(btnCerrarSesion);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AlumnoInternal ventanaMateria = new AlumnoInternal();
        escritorio.add(ventanaMateria);
        ventanaMateria.setVisible(true);
        ventanaMateria.moveToFront();
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        MateriaInternal ventanaMateria = new MateriaInternal();
        escritorio.add(ventanaMateria);
        ventanaMateria.setVisible(true);
        ventanaMateria.moveToFront();
        
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        VistaLogin ventanaLogin = new VistaLogin();
        ventanaLogin.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        CalificacionesInternal ventanaCalificacion = new CalificacionesInternal(usuario);
        escritorio.add(ventanaCalificacion);
        ventanaCalificacion.setVisible(true);
        ventanaCalificacion.moveToFront();
    }//GEN-LAST:event_btnCalificacionesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAlumnos;
    private javax.swing.JMenuItem btnCalificaciones;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnMaterias;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
